# vim:sw=2:et:

dist: xenial
sudo: false
language: erlang

addons:
  apt:
    packages:
      - xsltproc
      - python3

cache:
  apt: true

otp_release:
  - 21.3

before_script:
  - elixir --version
  # The checkout made by Travis is a "detached HEAD" and branches
  # information is missing. Our Erlang.mk's git_rmq fetch method relies
  # on it, so we need to restore it.
  #
  # We simply fetch master and, if it exists, v3.8.x branches. A branch
  # is created, pointing to the detached HEAD.
  - |
    git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
    git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
    git fetch upstream v3.8.x:v3.8.x || :
    git fetch upstream master:master || :

script:
  - make tests
